# Generated by Django 6.0.6 on 2026-07-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedDraTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meddra_concept_code', models.CharField(max_length=16)),
                ('term_type', models.CharField(max_length=8)),
                ('meddra_id', models.CharField(max_length=16)),
                ('term_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_name'], name='meddra_medd_normali_432d9b_idx'), models.Index(fields=['term_type'], name='meddra_medd_term_ty_8d7fcd_idx')],
                'constraints': [models.UniqueConstraint(fields=('meddra_concept_code', 'term_type', 'meddra_id', 'term_name'), name='unique_meddra_term_row')],
            },
        ),
    ]
