# Generated by Django 6.0.6 on 2026-07-02 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rxnorm_code', models.CharField(blank=True, max_length=64)),
                ('atc_code', models.CharField(blank=True, max_length=32)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meddra_code', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reactions', to='drugs.drug')),
            ],
            options={
                'unique_together': {('drug', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('evidence_source', models.CharField(blank=True, max_length=255)),
                ('source_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_source', to='drugs.drug')),
                ('target_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_target', to='drugs.drug')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_drug', 'target_drug'), name='unique_drug_interaction_pair')],
            },
        ),
    ]
