# Generated by Django 6.0.6 on 2026-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=32, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=16)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('drug_allergies', models.TextField(blank=True)),
                ('genetic_disorders', models.TextField(blank=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('symptoms', models.TextField(blank=True)),
                ('recommended_medication', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=64)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('treatment_effectiveness', models.CharField(blank=True, max_length=64)),
                ('adverse_reactions', models.CharField(blank=True, max_length=16)),
                ('recovery_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
